package com.skytrack.app.ui.theme

import androidx.compose.ui.graphics.Color

// ─── Light Mode – Notion-inspired warm neutrals ─────────────────────────────
val LightPrimary             = Color(0xFF37352F)
val LightOnPrimary           = Color(0xFFFFFFFF)
val LightPrimaryContainer    = Color(0xFFF7F6F3)
val LightOnPrimaryContainer  = Color(0xFF37352F)
val LightSecondary           = Color(0xFF787774)
val LightOnSecondary         = Color(0xFFFFFFFF)
val LightSecondaryContainer  = Color(0xFFF0EFEC)
val LightOnSecondaryContainer = Color(0xFF37352F)
val LightTertiary            = Color(0xFF2F80ED)
val LightOnTertiary          = Color(0xFFFFFFFF)
val LightTertiaryContainer   = Color(0xFFD6E4F7)
val LightOnTertiaryContainer = Color(0xFF1A3A6B)
val LightBackground          = Color(0xFFFFFFFF)
val LightOnBackground        = Color(0xFF37352F)
val LightSurface             = Color(0xFFFFFFFF)
val LightOnSurface           = Color(0xFF37352F)
val LightSurfaceVariant      = Color(0xFFF7F6F3)
val LightOnSurfaceVariant    = Color(0xFF787774)
val LightOutline             = Color(0xFFE7E7E5)
val LightOutlineVariant      = Color(0xFFF0EFEC)
val LightError               = Color(0xFFEB5757)
val LightOnError             = Color(0xFFFFFFFF)
val LightErrorContainer      = Color(0xFFFDE8E8)
val LightOnErrorContainer    = Color(0xFF5C1616)

// ─── Dark Mode – Notion dark theme ──────────────────────────────────────────
val DarkPrimary              = Color(0xFFEBECEC)
val DarkOnPrimary            = Color(0xFF2F3437)
val DarkPrimaryContainer     = Color(0xFF3F4447)
val DarkOnPrimaryContainer   = Color(0xFFEBECEC)
val DarkSecondary            = Color(0xFF9FA2A3)
val DarkOnSecondary          = Color(0xFF2F3437)
val DarkSecondaryContainer   = Color(0xFF43484B)
val DarkOnSecondaryContainer = Color(0xFFEBECEC)
val DarkTertiary             = Color(0xFF5C9CE6)
val DarkOnTertiary           = Color(0xFF1A2A3D)
val DarkTertiaryContainer    = Color(0xFF2A4A6B)
val DarkOnTertiaryContainer  = Color(0xFFD6E4F7)
val DarkBackground           = Color(0xFF2F3437)
val DarkOnBackground         = Color(0xFFEBECEC)
val DarkSurface              = Color(0xFF373C3F)
val DarkOnSurface            = Color(0xFFEBECEC)
val DarkSurfaceVariant       = Color(0xFF3F4447)
val DarkOnSurfaceVariant     = Color(0xFF9FA2A3)
val DarkOutline              = Color(0xFF43484B)
val DarkOutlineVariant       = Color(0xFF3F4447)
val DarkError                = Color(0xFFEB5757)
val DarkOnError              = Color(0xFFFFFFFF)
val DarkErrorContainer       = Color(0xFF5C1616)
val DarkOnErrorContainer     = Color(0xFFFDE8E8)

// ─── Flight-specific (unchanged) ────────────────────────────────────────────
val ProgressGold   = Color(0xFFFFA000)
val ProgressTrack  = Color(0xFF43484B)
val RouteBlue      = Color(0xFF5C9CE6)
val AircraftWhite  = Color(0xFFEBECEC)
val AltitudeCyan   = Color(0xFF39D0D8)
val SpeedGreen     = Color(0xFF56D364)

// ─── Semantic Colours ───────────────────────────────────────────────────────
val Success        = Color(0xFF2EA043)
val SuccessLight   = Color(0xFF56D364)
val Warning        = Color(0xFFD29922)
val WarningLight   = Color(0xFFE3B341)
val Info           = Color(0xFF5C9CE6)

// ─── Gradients ──────────────────────────────────────────────────────────────
val GradientStart  = Color(0xFF37352F)
val GradientEnd    = Color(0xFF2F3437)
